include: package:flutter/analysis_options_user.yaml

analyzer:
  errors:
    # implementation_imports: ignore
    # non_constant_identifier_names: ignore
    # unused_element: ignore
    # undefined_named_parameter: ignore
    # deprecated_member_use: ignore