name: flutter_architecture
description: A Flutter architecture project boilerplate.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^1.1.1
  meta: ^1.1.8
  dartz: ^0.9.1
  firebase_auth: ^0.16.0
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.5
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  flutter_bloc: ^4.0.0
  get_it: ^4.0.2
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.6+4
  image_cropper: ^1.2.2
  intl: ^0.16.1
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  json_serializable: ^3.3.0
  build_runner: ^1.8.1
  bloc_test: ^5.0.0
  intl_translation: ^0.17.9

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700