name: test
on:
  push:
    branches:
      - master
      # - development
jobs:
  test:
    runs-on: macos-latest
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17'
          channel: 'dev'
      # This action sets up a java environment
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter pub get
      - run: flutter clean
      # build Android version
      # - run: flutter build apk --debug --split-per-abi
      # This action will create a github release and optionally upload an artifact to it.
      # https://github.com/ncipollo/release-action
      # - name: Create a Release APK
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/apk/debug/*.apk,build/macos/Build/Products/Release/*.app"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      # build Flutter web version
      # - run: flutter build web
      # Handle the deploy process of your project to GitHub Pages.
      # https://github.com/JamesIves/github-pages-deploy-action
      # - uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      #     BASE_BRANCH: master
      #     BRANCH: gh-pages
      #     FOLDER: build/web