name: Build
on:
  push:
    tags:
      - '*'
    branches:
      - master
      - development
jobs:
  build:
    runs-on: macos-latest
    #Identifies any jobs that must complete successfully before this job will run.
    # needs: [test]
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      # This action sets up a java environment
      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # - run: flutter  config --enable-web
      - run: flutter pub get
      # build Android version
      - run: flutter build apk --debug --split-per-abi
      # This action will create a github release and optionally upload an artifact to it.
      # https://github.com/ncipollo/release-action
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.GH_TOKEN }}
      # build Flutter web version
      # - run: flutter build web
      # Handle the deploy process of your project to GitHub Pages.
      # https://github.com/JamesIves/github-pages-deploy-action
      # - uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #     BASE_BRANCH: master
      #     BRANCH: gh-pages
      #     FOLDER: build/web